import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from 'next/font/google'
import MainProvider from "@/MainProvider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const outfit = Outfit({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainProvider>
      <html lang="en">
        <body
          className={outfit.className}
        >
          {children}
        </body>
      </html>
    </MainProvider>
  );
}
